apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: simple-pipeline-2-remote-2
  namespace: openshift-gitops
spec:
  project: simple-apps-mc
  destination:
    namespace: simple-pipeline-2-2
    server: https://api.cluster-1.sandbox5426.opentlc.com:6443
  ignoreDifferences:
  - group: argoproj.io
    jsonPointers:
    - /status
    kind: Application
  - group: triggers.tekton.dev
    jsonPointers:
    - /status
    kind: EventListener
  - group: triggers.tekton.dev
    jsonPointers:
    - /status
    kind: TriggerTemplate
  - group: triggers.tekton.dev
    jsonPointers:
    - /status
    kind: TriggerBinding
  - group: route.openshift.io
    jsonPointers:
    - /spec/host
    kind: Route
  source:
    path: pipelines/simplePipeline-2/deployment
    targetRevision: main
    repoURL: https://github.com/marrober/simple-apps.git
  syncPolicy:
    automated: 
      prune: true 
      selfHeal: true 
      allowEmpty: false 
    syncOptions:  
    - Validate=true
    - CreateNamespace=true 
    - PrunePropagationPolicy=foreground 
    - PruneLast=true 
    retry:
      limit: 1 
      backoff:
        duration: 5s 
        factor: 2 
        maxDuration: 20s 