apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- argocd-management-app.yaml
- argocd-project-simple-apps.yaml
- argocd-application-local.yaml
- argocd-application-remote-1.yaml